openapi: 3.0.1
info:
  title: RequestCatcherAPI
  description: API Definition of RequestCatcherAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/requestCatcher
paths:
  /invoke:
    get:
      responses:
        default:
          description: Default response
  /healthz:
    get:
      responses:
        default:
          description: Default response
